# Hiero Configuration
spring.hiero.accountId=${HIERO_ACCOUNT_ID:0.0.8740886}
spring.hiero.privateKey=${HIERO_PRIVATE_KEY:a7c48aebf1437e11dfcbc9fbadaa5fa69753a57f1b9df553f51c310b947c83f4}
spring.hiero.network.name=${HIERO_NETWORK:hedera-testnet}
spring.hiero.topicId=${HIERO_TOPIC_ID:0.0.8806492}
spring.hiero.tokenId=${HIERO_TOKEN_ID:0.0.8824365}

# Server Configuration
server.port=8080

# Supabase Configuration
supabase.url=${SUPABASE_URL:https://mzkxiglnxmnpmliahsnh.supabase.co/rest/v1}
supabase.anonKey=${SUPABASE_ANON_KEY:sb_publishable_8fTKCnXNVP59XpYM-utHRQ_QTwFsIp5}

# Flutterwave Configuration
flw.publicKey=${FLW_PUBLIC_KEY:FLWPUBK_TEST-efddd3bb2150d48b7cda2154514e8d2f-X}
flw.secretKey=${FLW_SECRET_KEY:FLWSECK_TEST-bb76dcb7ead1d89e425f61e020662075-X}
